/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cbfd8ad0b7cd3340031067f
*
* You will get 10% discount for each one of your friends
* 
*/
using System;
using System.Collections.Generic;
using test.Support;
using Rg.Plugins.Popup.Pages;
using Rg.Plugins.Popup.Services;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace test.Extensions
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class PickerPopUp : PopupPage
    {
        #region Events

        public event EventHandler ItemSelectedEvent;

        #endregion

        public PickerPopUp()
        {
            InitializeComponent();

            // setting self BingingContext
            BindingContext = this;
        }

        public PickerPopUp(IEnumerable<BaseBindableObject> items) : this()
        {
            listView.ItemsSource = items;
        }

        void Dismiss_PopUp_Handler(object sender, EventArgs e)
        {
            PopupNavigation.Instance.PopAsync();
        }

        void ItemSelected_Handler(object sender, ItemTappedEventArgs e)
        {
            OnItemSelected(e.Item as BaseBindableObject);
            (sender as ListView).SelectedItem = null;
            PopupNavigation.Instance.PopAsync();
        }

        protected virtual void OnItemSelected(BaseBindableObject item)
        {
            ItemSelectedEvent?.Invoke(item, EventArgs.Empty);
        }
    }
}
