/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cbfd8ad0b7cd3340031067f
*
* You will get 10% discount for each one of your friends
* 
*/
using System;
using System.Threading.Tasks;
using test.Extension.Events;
using Xamarin.Forms;

namespace test.ViewModels
{
    public class LoginPageViewModel : BaseViewModel
    {
        #region Attributes and Properties

        string _username;
        string _password;

        public string Username
        {
            get { return _username; }
            set { SetValue(ref _username, value); }
        }

        public string Password
        {
            get { return _password; }
            set { SetValue(ref _password, value); }
        }

        #endregion

        #region Events

        public event EventHandler<LoginEventArgs> LoginError;

        #endregion

        public async Task Login()
        {
            OnLoadingStarted(EventArgs.Empty);

            //Try to execut login request
            if(await App.LoginService.LoginAsync(Username, Password))
                Application.Current.MainPage = new MasterPage();
            else
            {
                LoginEventArgs e = new LoginEventArgs("Incorrect Username or Password");
                OnLoginError(e);
            }

            OnLoadingEnded(EventArgs.Empty);
        }

        protected virtual void OnLoginError(LoginEventArgs e)
        {
            LoginError?.Invoke(this, e);
        }
    }
}