/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cbfd8ad0b7cd3340031067f
*
* You will get 10% discount for each one of your friends
* 
*/
using Rg.Plugins.Popup.Services;
using test.Extensions;
using test.Models;
using test.ViewModels;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;
using System.Threading.Tasks;

namespace test.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Profile : ContentPage
    {
        ProfilePageViewModel _viewModel
        {
            get { return BindingContext as ProfilePageViewModel; }
            set { BindingContext = value; }
        }

        public Profile()
        {
            InitializeComponent();

            ToolbarItems.Add(new ToolbarItem("Edit", null, Make_User_Editable));
        }

        public Profile(User user) : this()
        {
            BindingContext = new ProfilePageViewModel(user);

            _viewModel.LoadingStartedEvent += (sender, e) => { loading_view.IsVisible = true; };
            _viewModel.LoadingEndedEvent += (sender, e) => { Make_User_Editable(); loading_view.IsVisible = false; };

            if (string.IsNullOrWhiteSpace(entry_name.Text) && string.IsNullOrWhiteSpace(entry_lastname.Text) && string.IsNullOrWhiteSpace(entry_mail.Text))
                Make_User_Editable();
        }

        void Make_User_Editable()
        {
            entry_name.IsEnabled = !entry_name.IsEnabled;
            entry_lastname.IsEnabled = !entry_lastname.IsEnabled;
            entry_mail.IsEnabled = !entry_mail.IsEnabled;

            button_save.IsVisible = !button_save.IsVisible;
        }

        async Task Save_User_Handler(object sender, System.EventArgs e)
        {
            if (!string.IsNullOrWhiteSpace(entry_name.Text) && !string.IsNullOrWhiteSpace(entry_lastname.Text) && !string.IsNullOrWhiteSpace(entry_mail.Text))
                await _viewModel.UpdateUserInfo();
        }

        void Change_Password_Handler(object sender, System.EventArgs e)
        {
            PopupNavigation.Instance.PushAsync(new ChangePasswordPopUp());
        }
    }
}