/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cbfd8ad0b7cd3340031067f
*
* You will get 10% discount for each one of your friends
* 
*/
using test.Extensions;
using test.ViewModels;
using Rg.Plugins.Popup.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace test.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class RegisterNewUser : ContentPage
	{
        RegisterNewUserViewModel _viewModel
        {
            get { return BindingContext as RegisterNewUserViewModel; }
            set { BindingContext = value; }
        }

		public RegisterNewUser ()
		{
            InitializeComponent();

            picker_role.ItemsSource = new List<string> { "ADMIN", "USER" };

            // setting BindingContext
            _viewModel = new RegisterNewUserViewModel();

            _viewModel.LoadingStartedEvent += (sender, e) => { loading_view.IsVisible = true; };
            _viewModel.LoadingEndedEvent += async (sender, e) => 
            {
                loading_view.IsVisible = false;
                await Navigation.PopAsync();
            };
        }

        async Task Save_User_Handler(object sender, EventArgs e)
        {
            if(!entry_password.Text.Equals(entry_password_confirm.Text))
            {
                CustomAlertPopUp popUp = new CustomAlertPopUp("Passwords do not match");
                await PopupNavigation.Instance.PushAsync(popUp);
            } else
                await _viewModel.AddUser();

        }

        void Data_Changed_Handler(object sender, EventArgs e)
        {
            button_save.IsEnabled = 
                !string.IsNullOrEmpty(entry_username.Text) && !string.IsNullOrEmpty(entry_name.Text) &&
                !string.IsNullOrEmpty(entry_lastname.Text) && !string.IsNullOrEmpty(entry_mail.Text) &&
                !string.IsNullOrEmpty(entry_password.Text) && !string.IsNullOrEmpty(entry_password_confirm.Text) &&
                picker_role.SelectedItem != null;
        }
    }
}