/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5cbfd8ad0b7cd3340031067f
*
* You will get 10% discount for each one of your friends
* 
*/
using System;
using Newtonsoft.Json;
using test.Support;

namespace test.Models.Base
{
    public class UserBase : BaseBindableObject
    {
         // Id Start
		string _id;
		[JsonProperty(PropertyName = "_id")]
		public string Id
		{
			get { return _id; }
			set { SetValue(ref _id, value); }
		}
		 // Id End 
        
        string mail;
        [JsonProperty(PropertyName = "mail")]
        public string Mail
        {
            get { return mail; }
            set { SetValue(ref mail, value); }
        }
        
        string name;
        [JsonProperty(PropertyName = "name")]
        public string Name
        {
            get { return name; }
            set { SetValue(ref name, value); }
        }
        
        string password;
        [JsonProperty(PropertyName = "password")]
        public string Password
        {
            get { return password; }
            set { SetValue(ref password, value); }
        }
        
        string surname;
        [JsonProperty(PropertyName = "surname")]
        public string Surname
        {
            get { return surname; }
            set { SetValue(ref surname, value); }
        }
        
        string username;
        [JsonProperty(PropertyName = "username")]
        public string Username
        {
            get { return username; }
            set { SetValue(ref username, value); }
        }
        
        string[] roles;
        [JsonProperty(PropertyName = "roles")]
        public string[] Roles
        {
            get { return roles; }
            set { SetValue(ref roles, value); }
        }
        

        string token;
        [JsonProperty(PropertyName = "token")]
        public string Token
        {
            get{ return token; }
            set{ SetValue(ref token, value); }
        }
    }
}